[project]
name = "adventofpwn2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "absl-py>=2.3.1",
    "capstone>=5.0.6",
    "lief>=0.17.1",
    "triton-library>=1.0.0rc4",
]
